jobs:
  - name: job-foo
    type: runSh
    steps:
      - IN: img-busybox
      - IN: repo-skylark05-pipelines
      - TASK:
        - script: . /build/IN/repo-skylark05-pipelines/gitRepo/foo.sh
  - name: job-bar
    type: runSh
    steps:
      - IN: img-busybox
      - IN: repo-skylark05-pipelines
      - TASK:
        - script: . /build/IN/repo-skylark05-pipelines/gitRepo/foo.sh
  - name: bar-1
    type: runSh
    steps:
      - IN: job-bar
      - IN: repo-skylark05-pipelines
      - TASK:
        - script: . /build/IN/repo-skylark05-pipelines/gitRepo/foo.sh
  - name: bar-2
    type: runSh
    steps:
      - IN: job-bar
      - IN: repo-skylark05-pipelines
      - TASK:
        - script: . /build/IN/repo-skylark05-pipelines/gitRepo/foo.sh
  - name: bar-21
    type: runSh
    steps:
      - IN: bar-2
      - IN: repo-skylark05-pipelines
      - TASK:
        - script: . /build/IN/repo-skylark05-pipelines/gitRepo/foo.sh
  - name: foo-1
    type: runSh
    steps:
      - IN: job-foo
      - IN: repo-skylark05-pipelines
      - TASK:
        - script: . /build/IN/repo-skylark05-pipelines/gitRepo/foo.sh
